apiVersion : apps/v1
kind: Deployment
metadata:
  name: ratings-api 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings-api
  template:
    metadata:
      labels:
        app: ratings-api 
    spec:
      containers:
        - name: ratingsapi 
          image: acrerc.azurecr.io/ratings-api:v1
          ports:
          - containerPort: 3000